[2024-04-12T22:27:34.969+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T22:27:34.994+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_clickhouse_dag.create_pet_table scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-04-12T22:27:35.002+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_clickhouse_dag.create_pet_table scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-04-12T22:27:35.003+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-12T22:27:35.016+0000] {taskinstance.py:2327} INFO - Executing <Task(ClickHouseOperator): create_pet_table> on 2024-02-02 00:00:00+00:00
[2024-04-12T22:27:35.022+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=580) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-12T22:27:35.024+0000] {standard_task_runner.py:63} INFO - Started process 582 to run task
[2024-04-12T22:27:35.023+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_clickhouse_dag', 'create_pet_table', 'scheduled__2024-02-02T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/test_clickhouse_dag.py', '--cfg-path', '/tmp/tmpmuyezgy5']
[2024-04-12T22:27:35.026+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask create_pet_table
[2024-04-12T22:27:35.070+0000] {task_command.py:426} INFO - Running <TaskInstance: test_clickhouse_dag.create_pet_table scheduled__2024-02-02T00:00:00+00:00 [running]> on host 5a7e88883700
[2024-04-12T22:27:35.150+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_clickhouse_dag' AIRFLOW_CTX_TASK_ID='create_pet_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-02T00:00:00+00:00'
[2024-04-12T22:27:35.151+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T22:27:35.184+0000] {base.py:84} INFO - Using connection ID 'clickhouse_local_test' for task execution.
[2024-04-12T22:27:35.185+0000] {clickhouse.py:79} INFO - 
            CREATE TABLE IF NOT EXISTS pet (
            pet_id INT NOT NULL PRIMARY KEY,
            name VARCHAR NOT NULL,
            pet_type VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            owner VARCHAR NOT NULL);
          
[2024-04-12T22:27:35.186+0000] {connection.py:408} WARNING - Failed to connect to localhost:9000
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 396, in connect
    return self._init_connection(host, port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 326, in _init_connection
    self.socket = self._create_socket(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 297, in _create_socket
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 288, in _create_socket
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-04-12T22:27:35.188+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T22:27:35.189+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
           ^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 314, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 301, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 254, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 417, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. Connection refused (localhost:9000)
[2024-04-12T22:27:35.201+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=test_clickhouse_dag, task_id=create_pet_table, execution_date=20240202T000000, start_date=20240412T222734, end_date=20240412T222735
[2024-04-12T22:27:35.213+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task create_pet_table (Code: 210. Connection refused (localhost:9000); 582)
[2024-04-12T22:27:35.239+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-12T22:27:35.261+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-12T22:27:35.265+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-15T10:00:21.210+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T10:00:21.254+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_clickhouse_dag.create_pet_table scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-04-15T10:00:21.269+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_clickhouse_dag.create_pet_table scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-04-15T10:00:21.270+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T10:00:21.290+0000] {taskinstance.py:2327} INFO - Executing <Task(ClickHouseOperator): create_pet_table> on 2024-02-02 00:00:00+00:00
[2024-04-15T10:00:21.298+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=893) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T10:00:21.300+0000] {standard_task_runner.py:63} INFO - Started process 895 to run task
[2024-04-15T10:00:21.300+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_clickhouse_dag', 'create_pet_table', 'scheduled__2024-02-02T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/test_clickhouse_dag.py', '--cfg-path', '/tmp/tmpp334e43m']
[2024-04-15T10:00:21.303+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask create_pet_table
[2024-04-15T10:00:21.364+0000] {task_command.py:426} INFO - Running <TaskInstance: test_clickhouse_dag.create_pet_table scheduled__2024-02-02T00:00:00+00:00 [running]> on host 6f78617af605
[2024-04-15T10:00:21.531+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_clickhouse_dag' AIRFLOW_CTX_TASK_ID='create_pet_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-02T00:00:00+00:00'
[2024-04-15T10:00:21.532+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T10:00:21.566+0000] {base.py:84} INFO - Using connection ID 'clickhouse_local_test' for task execution.
[2024-04-15T10:00:21.568+0000] {clickhouse.py:79} INFO - 
                CREATE TABLE employee
            (
                emp_no  UInt32 NOT NULL
                                        )
            ENGINE = MergeTree()
            PRIMARY KEY (emp_no);
          
[2024-04-15T10:00:21.584+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T10:00:21.587+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clickhouse_plugin/operators/clickhouse.py", line 83, in execute
    return self._hook_execute()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clickhouse_plugin/operators/clickhouse.py", line 69, in _hook_execute
    return hook.execute(
           ^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_clickhouse_plugin/hooks/clickhouse.py", line 80, in execute
    last_result = conn.execute(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 382, in execute
    rv = self.process_ordinary_query(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 213, in receive_result
    return result.get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 229, in packet_generator
    packet = self.receive_packet()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 246, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 57.
DB::Exception: Table default.employee already exists. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0xa6fecf3 in /usr/bin/clickhouse
2. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) @ 0x139d47d6 in /usr/bin/clickhouse
3. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x139cec0d in /usr/bin/clickhouse
4. DB::InterpreterCreateQuery::execute() @ 0x139d64ab in /usr/bin/clickhouse
5. ? @ 0x13d1434c in /usr/bin/clickhouse
6. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
7. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
8. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
9. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
10. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
11. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
13. ? @ 0x7ff28e4f8609 in ?
14. __clone @ 0x7ff28e41f293 in ?

[2024-04-15T10:00:21.616+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=test_clickhouse_dag, task_id=create_pet_table, execution_date=20240202T000000, start_date=20240415T100021, end_date=20240415T100021
[2024-04-15T10:00:21.642+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task create_pet_table (Code: 57.
DB::Exception: Table default.employee already exists. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0xa6fecf3 in /usr/bin/clickhouse
2. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&) @ 0x139d47d6 in /usr/bin/clickhouse
3. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x139cec0d in /usr/bin/clickhouse
4. DB::InterpreterCreateQuery::execute() @ 0x139d64ab in /usr/bin/clickhouse
5. ? @ 0x13d1434c in /usr/bin/clickhouse
6. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
7. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
8. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
9. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
10. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
11. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
13. ? @ 0x7ff28e4f8609 in ?
14. __clone @ 0x7ff28e41f293 in ?
; 895)
[2024-04-15T10:00:21.675+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T10:00:21.713+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T10:00:21.724+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-15T13:15:59.225+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T13:15:59.269+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_clickhouse_dag.create_pet_table scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-04-15T13:15:59.283+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_clickhouse_dag.create_pet_table scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-04-15T13:15:59.284+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T13:15:59.304+0000] {taskinstance.py:2327} INFO - Executing <Task(ClickHouseOperator): create_pet_table> on 2024-02-02 00:00:00+00:00
[2024-04-15T13:15:59.314+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T13:15:59.316+0000] {standard_task_runner.py:63} INFO - Started process 85 to run task
[2024-04-15T13:15:59.317+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_clickhouse_dag', 'create_pet_table', 'scheduled__2024-02-02T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/test_clickhouse_dag.py', '--cfg-path', '/tmp/tmpiu7ele_h']
[2024-04-15T13:15:59.322+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask create_pet_table
[2024-04-15T13:15:59.393+0000] {task_command.py:426} INFO - Running <TaskInstance: test_clickhouse_dag.create_pet_table scheduled__2024-02-02T00:00:00+00:00 [running]> on host 4c01df574902
[2024-04-15T13:15:59.634+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_clickhouse_dag' AIRFLOW_CTX_TASK_ID='create_pet_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-02T00:00:00+00:00'
[2024-04-15T13:15:59.637+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T13:15:59.707+0000] {base.py:84} INFO - Using connection ID 'clickhouse_local_test' for task execution.
[2024-04-15T13:15:59.710+0000] {clickhouse.py:79} INFO - 
                CREATE TABLE IF NOT EXISTS employee
            (
                emp_no  UInt32 NOT NULL
                                        )
            ENGINE = MergeTree()
            PRIMARY KEY (emp_no);
          
[2024-04-15T13:15:59.730+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T13:15:59.786+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=test_clickhouse_dag, task_id=create_pet_table, execution_date=20240202T000000, start_date=20240415T131559, end_date=20240415T131559
[2024-04-15T13:15:59.853+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-15T13:15:59.883+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T13:15:59.892+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
